# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
tabulate2dCpp <- function(x, xmin, xmax, y, ymin, ymax) {
    .Call('_smmtools_tabulate2dCpp', PACKAGE = 'smmtools', x, xmin, xmax, y, ymin, ymax)
}

